CREATE DATABASE verbum_domini;

CREATE TABLE bible(
  id INT NOT NULL,
  name CHARACTER VARYING(100) NOT NULL,
  language CHARACTER VARYING(50) NOT NULL,
  url CHARACTER VARYING(200),
  edition CHARACTER VARYING(100),
  printed_source CHARACTER VARYING(300),
  eletronic_transcription_source CHARACTER VARYING(200),
  eletronic_transcription_source_url CHARACTER VARYING(200),
  copyright CHARACTER VARYING(200),
  CONSTRAINT bible_pkey PRIMARY KEY(id),
  CONSTRAINT unique_bible_name UNIQUE (name)
);

CREATE TABLE book(
  id INT NOT NULL,
  bible_fk INT NOT NULL,
  name CHARACTER VARYING(100) NOT NULL,
  CONSTRAINT book_pkey PRIMARY KEY(id),
  CONSTRAINT fkc_bible_book FOREIGN KEY (bible_fk)
      REFERENCES bible (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE chapter(
  id INT NOT NULL,
  number CHARACTER VARYING(5) NOT NULL,
  book_fk INT NOT NULL,
  CONSTRAINT chapter_pkey PRIMARY KEY(id),
  CONSTRAINT fkc_book_chapter FOREIGN KEY (book_fk)
      REFERENCES book (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE verse(
  id INT NOT NULL,
  chapter_fk INT NOT NULL,
  number CHARACTER VARYING(5) NOT NULL,
  text CHARACTER VARYING(10000) NOT NULL,
  CONSTRAINT verse_pkey PRIMARY KEY(id),
  CONSTRAINT fkc_chapter_verse FOREIGN KEY (chapter_fk)
      REFERENCES chapter (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE annotation(
  id INT NOT NULL,
  chapter_fk INT NOT NULL,
  number CHARACTER VARYING(5) NOT NULL,
  text CHARACTER VARYING(5000) NOT NULL,
  CONSTRAINT annotation_pkey PRIMARY KEY(id),
  CONSTRAINT fkc_chapter_annotation FOREIGN KEY (chapter_fk)
      REFERENCES chapter (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE SEQUENCE bible_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 2147483647
  START 1
  CACHE 1;

CREATE SEQUENCE book_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 2147483647
  START 1
  CACHE 1;

CREATE SEQUENCE chapter_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 2147483647
  START 1
  CACHE 1;

CREATE SEQUENCE verse_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 2147483647
  START 1
  CACHE 1;

CREATE SEQUENCE annotation_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 2147483647
  START 1
  CACHE 1;