#%RAML 0.8
---
title: "Holy bible REST API"
baseUri: http://localhost:8081/verbum_domini/apirest
version: v1
schemas:
  - bible: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "Holy bible.",
         "$linkedData": {
           "books": {
             "schema": "book",
             "type": "collection",
             "path": ["/bibles", "/{language}", "/books"]
           }
         },
         "properties": {
           "bibleId": { "type": "integer", "required": true },
           "name": { "type": "string", "required": true },
           "language": { "type": "string", "required": true },
           "url": { "type": "string", "required": false },
           "edition": { "type": "string", "required": false },
           "printedSource": { "type": "string", "required": true },
           "eletronicTranscriptionSource": { "type": "string", "required": false },
           "eletronicTranscriptionSourceUrl": { "type": "string", "required": false },
           "copyright": { "type": "string", "required": false }
         }
      }
  - bibles: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "Available Holy Bible collection.",
         "properties": {
           "size":  { "type": "integer", "required": true },
           "bibles": {
             "type": "array",
             "items": { "$ref": "bible" }
           }
         }
       }
  - book: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "Book within the Holy Bible.",
         "$linkedData": {
           "chapters": {
             "schema": "chapter",
             "type": "collection",
             "path": ["/bibles", "/{language}", "/books", "/{id}", "/chapters"]
           },
           "bible": {
             "schema": "bible",
             "type": "single",
             "path": ["/bibles", "/{bibleId}"]
           }
         },
         "properties": {
           "bookId": { "type": "integer", "required": true },
           "name": { "type": "string", "required": true },
           "bibleId": { "type": "integer", "required": true }
         }
      }
  - books: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "Available books within the Holy Bible.",
         "properties": {
           "size":  { "type": "integer", "required": true },
           "books": {
             "type": "array",
             "items": { "$ref": "book" }
           }
         }
       }

resourceTypes:
  - base:
      get?:
        responses: &standardResponses
          200:
            description: OK
  - collection:
      type: base
      get:
        is: [ paged ]
  - typedCollection:
      type: collection
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<collectionSchema>>
  - member:
      type: base
      get:
  - typedMember:
      type: member
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>

traits:
  - paged:
      displayName: paged
      queryParameters:
        start:
          displayName: start
          description: The first page to return
          type: integer
        pages:
          displayName: pages
          description: The number of pages to return
          type: integer

/bibles:
  type: { typedCollection: { schema: bible, collectionSchema: bibles } }
  /{bibleId}:
    type: { typedMember: { schema: bible } }
    /books:
      type: { typedCollection: { schema: book, collectionSchema: books } }
      /{bookId}:
        type: { typedMember: { schema: book } }